{{- if and (.Values.appConfigValues.publicEventsApiEnabled) (not .Values.cartoConfigValues.onlyRunRouter) (.Values.publicEventsApi.autoscaling.enabled) }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "carto.publicEventsApi.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: public-events-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  minReplicas: {{ .Values.publicEventsApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.publicEventsApi.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "carto.publicEventsApi.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.publicEventsApi.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
