{{- if and (.Values.appConfigValues.aiFeaturesEnabled) (not .Values.cartoConfigValues.onlyRunRouter) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "carto.aiProxy.configmapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: aiproxy
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  AUTH0_AUDIENCE: "carto-cloud-native-api"
  AUTH0_DOMAIN: {{ .Values.cartoConfigValues.cartoAuth0CustomDomain | quote }}
  AUTH0_NAMESPACE: "http://app.carto.com"
  AI_API_URL: "http://{{ include "carto.aiApi.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
  {{- if not .Values.commonBackendServiceAccount.enableGCPWorkloadIdentity }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ include "carto.google.secretMountAbsolutePath" . | quote }}
  {{- end }}
  {{- if .Values.externalProxy.enabled }}
  HTTP_PROXY: {{ include "carto.proxy.computedConnectionString" . | quote }}
  http_proxy: {{ include "carto.proxy.computedConnectionString" . | quote }}
  HTTPS_PROXY: {{ include "carto.proxy.computedConnectionString" . | quote }}
  https_proxy: {{ include "carto.proxy.computedConnectionString" . | quote }}
  GRPC_PROXY: {{ include "carto.proxy.computedConnectionString" . | quote }}
  grpc_proxy: {{ include "carto.proxy.computedConnectionString" . | quote }}
  NODE_TLS_REJECT_UNAUTHORIZED: {{ ternary "1" "0" .Values.externalProxy.sslRejectUnauthorized | quote }}
  {{- if gt (len .Values.externalProxy.excludedDomains) 0 }}
  NO_PROXY: {{ join "," .Values.externalProxy.excludedDomains | quote }}
  no_proxy: {{ join "," .Values.externalProxy.excludedDomains | quote }}
  {{- end }}
  {{- end }}
  LITELLM_DATABASE_HOST: {{ include "carto.postgresql.host" . | quote }}
  LITELLM_DATABASE_USERNAME: {{ include "carto.postgresql.user" . | quote }}
  LITELLM_DATABASE_NAME: {{ .Values.externalPostgresql.aiProxyDatabaseName | quote }}
  LITELLM_DATABASE_PORT: {{ include "carto.postgresql.port" . | quote }}
  LITELLM_DATABASE_SSL_MODE: {{ include "carto.aiProxy.databaseSslMode" . | quote }}
  LITELLM_DATABASE_SSL_CA_PATH: {{ include "carto.postgresql.configMapMountAbsolutePath" . | quote }}
  LITELLM_LOG_LEVEL: {{ ternary "DEBUG" "INFO" (eq .Values.appConfigValues.logLevel "debug") | quote }}
  LITELLM_MIGRATION_DIR: "/tmp/prisma/migrations"
  LITELLM_MODE: "PRODUCTION"
  LITELLM_REDIS_DB: "1"
  LITELLM_REDIS_HOST: {{ include "carto.redis.host" . | quote }}
  LITELLM_REDIS_PORT: {{ include "carto.redis.port" . | quote }}
  LITELLM_REDIS_TLS_ENABLED: {{ .Values.externalRedis.tlsEnabled | quote }}
  LITELLM_VERTEXAI_PROJECT: {{ .Values.cartoConfigValues.selfHostedGcpProjectId | quote }}
  LITELLM_VERTEXAI_LOCATION: {{ .Values.cartoConfigValues.selfHostedGcpProjectRegion | quote }}
  LITELLM_TENANT_ID: {{ .Values.cartoConfigValues.selfHostedTenantId | quote }}
  LITELLM_NON_ROOT: true
  LITELLM_APP_MIGRATIONS_DIR: "/app/migrations"
  SERVER_ROOT_PATH: "/litellm"
  {{- if and .Values.externalProxy.enabled (or .Values.externalProxy.sslCA .Values.externalProxy.sslCAConfigmap.name) }}
  # aiproxy python httpx requirement
  SSL_CERT_FILE: {{ include "carto.proxy.configMapMountAbsolutePath" . | quote }}
  {{- end }}
  XDG_CACHE_HOME: "/app/.cache/prisma"
  NPM_CONFIG_CACHE: "/tmp/.npm"
{{- end }} 
