{{- if and (.Values.appConfigValues.aiFeaturesEnabled) (.Values.aiProxy.podDisruptionBudget.enabled) }}
---
apiVersion: {{ .Values.global.kubernetesPolicyVersion }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "carto.aiProxy.fullname" . }}-pdb
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: aiproxy
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.aiProxy.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.aiProxy.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.aiProxy.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.aiProxy.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/name: aiproxy
{{- end }} 
